name: 📄

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "*" ]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: branch
      - name: Display branch name
        shell: bash
        run: echo ${{ steps.branch.outputs.branch }}
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          sudo apt-get install doxygen cmake -y
          doxygen -w html header.html d.html doxygen.css
          echo done
          ls -r
          mkdir -p ${{ steps.branch.outputs.branch }}
          rm -r ${{ steps.branch.outputs.branch }}/*
          mv -v doc ${{ steps.branch.outputs.branch }}/
          #rm -r doc
          git config --global user.email "tobid7@outlook.de"
          git config --global user.name "Tobi-D7"
          echo tobid7
          git stage *
          echo staged
          git commit -m "Documentation1"
          git tag doc
          echo commited
          git push origin main
          echo pushed
